### PR TITLE
Fix github unicorn error and cache

### PR DESCRIPTION
**Pull request by soupi**
This fixes:

1. Github's unicorn error when trying to "show js" or press the compile button
2. Fix cache string - will now try to use the cache string to load previously cached code and backend settings

Changes can be viewed [here](https://soupi.github.io/trypurescript).

### CODE REVIEW

**Comment by paf31** [comment]
Thanks!

**Comment by paf31** [comment]
Actually now I always get an empty input on load.

**Comment by soupi** [comment]
That's weird, it works for me on computer and mobile, can you try a hard refresh or something?

**Comment by soupi** [comment]
It appears that what you describe indeed happen on chromium (not on firefox which i use) so now i have a way to replicate. Will work on this tonight.

**Pull request merged**
