### PR TITLE
es-module-shims 1.5.12

### PR DESCRIPTION
**Pull request by andys8**
Version 1.5.12 is currently - including the latest bug fix 1.5.15 - the best version for the project where the examples work in all tested browsers.

See these discussions for more details:

* <https://github.com/purescript/trypurescript/pull/297#issuecomment-1214194277>
* <https://github.com/guybedford/es-module-shims/issues/324#issuecomment-1214452714>

### CODE REVIEW

**Review by JordanMartinez — APPROVED** [review]
I've verified that this works for me locally.

**Comment by JordanMartinez** [comment]
@andys8 Mind adding a changelog entry for this?

**Comment by andys8** [comment]
7f2045528f8b5e5666ea31b34c828a6369bc31f3 :heavy_check_mark:

**Comment by JordanMartinez** [comment]
@natefaubion Can I get an approval on this?

**Review by natefaubion — APPROVED** [review]

**Pull request merged**
