### PR TITLE
Bug fixes - no output in Firefox/Safari & crazy scroll bars

### PR DESCRIPTION
**Pull request by LiamGoodacre**
It appears that `innerText` is not supported in these browsers.
However `appendChild` and `createTextNode` appear to have better support: http://caniuse.com/#search=createTextNode

### CODE REVIEW

**Comment by LiamGoodacre** [comment]
Just noticed that it used to use `createTextNode` what was the reason for switching to `innerText`?
https://github.com/purescript/trypurescript/commit/27e34bcd69752bbb856085ecc0af3e0b8764f338#diff-42f69825340f0b5fa628d80900a46daaL63

**Comment by LiamGoodacre** [comment]
This look okay @paf31 ? :smiley:

**Comment by paf31** [comment]
Looks good, but I don't remember why I changed this. Did you test it in Chrome too?

**Comment by LiamGoodacre** [comment]
Yes sorry I should have said: tested with Chrome, Firefox, and Safari.  But I don't have access to IE here.

**Comment by LiamGoodacre** [comment]
Tried IE 11, but neither my updates nor the existing site display anything - so I haven't made it any worse there...

**Comment by paf31** [comment]
Thanks! We can try and figure out IE11 separately then.

**Comment by paf31** [comment]
I'm not sure if this works on iOS. The scrolling seems messed up.

**Pull request merged**
