### PR TITLE
Try adding flare

### LINKED ISSUE #103: Flare backend version
The flare backend appears to be on version `3.0.0`.

The bower says it's using `3.2.0`: https://github.com/purescript/trypurescript/blob/ebf1a244cd2b58d115d56378cb4ab9716da4e3cf/bower.json#L27. `textarea` was added in `3.1.0`: https://github.com/sharkdp/purescript-flare/releases/tag/v3.1.0 (and still exists in `3.2.0`: https://pursuit.purescript.org/packages/purescript-flare/3.2.0/docs/Flare#v:textarea). But if you try to import `textarea`, it fails: http://try.purescript.org/?gist=a02503ed103a29e8212811b5140ecda0.

I'm not sure what to do to fix it or I would have sent a PR.

### PR DESCRIPTION
**Pull request by joneshf**
Might fix #103 

I don't have any clue what I'm doing. I can't figure out how to serve up this version of flare locally to test. @paf31 Maybe you can?

Will need to change the `set` and `source` once https://github.com/purescript/package-sets/pull/101 is merged

### CODE REVIEW

**Comment by paf31** [comment]
For reference, here is the current `bower.json` file:

```json
{
  "name": "tryflare",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "output"
  ],
  "dependencies": {
    "purescript-flarecheck": "^2.0.0",
    "purescript-console": "^2.0.0",
    "purescript-const": "^2.0.0",
    "purescript-exists": "^2.0.0",
    "purescript-free": "^3.0.1",
    "purescript-graphs": "^2.0.0",
    "purescript-profunctor": "^2.0.0",
    "purescript-quickcheck": "^3.1.1",
    "purescript-semirings": "^3.0.0",
    "purescript-validation": "^2.0.0"
  }
}
```

We also need to update the examples. @sharkdp Do you have time to look at that?

**Comment by sharkdp** [comment]
> We also need to update the examples. @sharkdp Do you have time to look at that?

Yes. I can update the examples when the new backend goes live.

**Comment by joneshf** [comment]
@paf31 what should I do with that `bower.json`?

**Comment by paf31** [comment]
I'm just letting you know what other packages are available right now so we don't lose any. You probably don't need to add all of those, but maybe some.

**Comment by joneshf** [comment]
Add some of them to what?

Sorry for being dense about this, but I really don't know what I'm doing :disappointed:.

**Comment by paf31** [comment]
To the `psc-package.json` file. That file replaces `bower.json` now, so if we need all of the same libraries, that's how we have to pull them in.

**Comment by joneshf** [comment]
I'm sorry, I tried to work with this more and just ended up getting more and more frustrated. I've tried following your directions here and in the other issues and thank you for trying to explain things to me. But, I don't know how to contribute to this repo properly and don't want to be responsible for updating flare's backend anymore.

I'll add `flarecheck` to the package-set since it's not in there yet.

**Comment by joneshf** [comment]
Actually, I'm not going to add `flarecheck` since `sparkle` was just added, and I think `sparkle` replaces `flarecheck`. So i'm leaving it to @sharkdp to decide.

**Pull request closed without merging**
