### PR TITLE
update purescript dep to purs-0.11.5

### PR DESCRIPTION
**Pull request by matthewleon**
addresses https://github.com/purescript/trypurescript/issues/77

This compiles for me. Not sure if there is any other testing I should do?

### CODE REVIEW

**Comment by paf31** [comment]
We should probably also update the core library versions, but that's not a big deal.

Thanks!

**Comment by matthewleon** [comment]
> We should probably also update the core library versions

FWIW I've gone ahead and updated the Stack LTS and one of the fixed dep versions.

**Comment by paf31** [comment]
Oh, sorry, I meant the PureScript library dependencies, but it's good to update these too.

**Comment by paf31** [comment]
This is the line which needs to be updated:

https://github.com/purescript/trypurescript/blob/eaecf651c6a311e771ed025053cb08fa5a5b1f67/staging/core/psc-package.json#L3

**Comment by matthewleon** [comment]
> This is the line which needs to be updated:

Done. Thanks.

**Pull request closed without merging**
