### PR TITLE
Add PureScript & Package Set version info

### LINKED ISSUE #149: Clearly indicate compiler version and package set in use

### PR DESCRIPTION
**Pull request by JordanMartinez**
**Description of the change**

Fixes #149. Screenshots below. CI tests (in progress) should prove that checks work:

Normal view:
image

Mobile view:
image

---

**Checklist:**

- [ ] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0 by @)")
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Client CI should fail because the `purs` version is `0.15.3` when it should be `0.15.2`. Once that build fails, I'll check again with the package set version differing.

**Comment by JordanMartinez** [comment]
Client CI successfully failed with the below error message:
```
< pursVersion = "v0.15.3"
---
> pursVersion = "v0.15.2"
PureScript and/or package set versions in "client/src/Try/SharedConfig.purs"
do not match the versions extracted from "stack.yaml" and "staging/packages.dhal
```
Now testing the package set version diff

**Comment by JordanMartinez** [comment]
Package set version CI check successfully failed with the following error:
```
< packageSetVersion = "0.15.3-20220531"
---
> packageSetVersion = "0.15.2-20220531"
PureScript and/or package set versions in "client/src/Try/SharedConfig.purs"
do not match the versions extracted from "stack.yaml" and "staging/packages.dhall".
Please run "cd client && npm run updateConfigVersions". CI will fail until then.
```

**Comment by JordanMartinez** [comment]
This PR is ready for review.

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
