### PR TITLE
Add a section for development to README

### PR DESCRIPTION
**Pull request by rintcius**

### CODE REVIEW

**Comment by rintcius** [comment]
BTW I have added `npm run bundle` but the `open index.html` part doesn't work for me (because it's opening `file://` instead of `http://`). Anything I I'm missing?

**Comment by sharkdp** [comment]
> but the open index.html part doesn't work for me

Same for me. I think it should be removed from `package.json`.

**Comment by paf31** [comment]
Fantastic, thanks!

I agree about removing the `index.html` command.

**Comment by rintcius** [comment]
@paf31 did you mean to close it without merging?

**Comment by paf31** [comment]
No, sorry.

**Pull request merged**
