### PR TITLE
Add Try Flare

### PR DESCRIPTION
**Pull request by sharkdp**
This adds externs files and a `flare.conf` file in order to run a "Try Flare" server.

Some of the included packages:
- purescript-flare
- purescript-flarecheck
- purescript-signal
- purescript-drawing
- purescript-smolder

Note: not all of the modules which are included in the `core`-bundle are included here.

### CODE REVIEW

**Comment by paf31** [comment]
Thanks! I'll deploy this now.

**Comment by paf31** [comment]
Here you go: https://compile.purescript.org/flare

**Comment by sharkdp** [comment]
Wow, that was fast! Thanks!

I will upload a first version of the client soon.

**Comment by paf31** [comment]
No problem, it's mostly copy and paste at this point :smile: 

Looking forward to trying out the client app!

**Comment by sharkdp** [comment]
A preview of the client is online: http://sharkdp.github.io/try-flare/

I will work more on this in the next few days. Thanks again!

**Comment by paf31** [comment]
Looks great already!

**Pull request merged**
