### PR TITLE
Update index.css

### PR DESCRIPTION
**Pull request by drets**
Make it a bit more mobile friendly. Close the PR if it's not useful :smiley:

### CODE REVIEW

**Comment by paf31** [comment]
Can you please link to this so we can try it out? Thanks.

**Comment by drets** [comment]
Sorry, I didn't get what “link to this” means.

Before:
selection_218
After:
selection_220

Feel free to close it if it's not that useful.

**Comment by paf31** [comment]
I mean can you please link to a working copy? Like on GitHub pages or something.

**Comment by drets** [comment]
Gotcha: https://drets.github.io/trypurescript/?session=afd19167-9ddf-fb0e-5a6d-d9e660804d91

**Comment by paf31** [comment]
Thanks! I tried this on iOS, and it looks great in portrait, but not in landscape unfortunately.

We also need to fix the scroll issue, but we can deal with that separately.

**Comment by drets** [comment]
We can limit it only to portrait (till 480px width) if you wish :wink: 
(but it feels a bit hacky)

**Comment by drets** [comment]
Deployed.

**Comment by paf31** [comment]
Thanks!

**Comment by soupi** [comment]
I like it! thanks!

**Pull request merged**
