### PR TITLE
add try-mathbox psc-package (package set psc-0.11.6)

### PR DESCRIPTION
**Pull request by rintcius**

### CODE REVIEW

**Comment by rintcius** [comment]
Client part in #104

**Comment by paf31** [comment]
Thanks!

**Comment by paf31** [comment]
Deployed, thanks!

@joneshf @sharkdp You might find this useful as an example. I'll try to improve the docs as well.

**Comment by joneshf** [comment]
So, just add a psc-package? Does anything need to be deleted?

**Comment by paf31** [comment]
You would need to

- find or create a package set with the version of flare you want
- make a local psc-package config and compile it
- pass the source files to the trypurescript executable and test locally
- update the gist id in the client to point to one which works with that version of flare (I believe the current ones are under @sharkdp's account)

**Pull request merged**
