### PR TITLE
Bump version to 0.12

### PR DESCRIPTION
**Pull request by natefaubion**

### CODE REVIEW

**Comment by natefaubion** [comment]
I don't fully understand this failure. It appears to build/install fine locally with these constraints. Any ideas?

**Comment by natefaubion** [comment]
Exit code 137 appears to be because it was kill -9ed, usually for using too many resources.

**Comment by natefaubion** [comment]
I think core is the only backend that is buildable. Is there anything I should do on the API side to disable the others? Or is that purely a `github-pages` thing?

**Comment by paf31** [comment]
In the interests of getting this released, I think we should focus only on the core package set.  It's a change in the client code.

**Comment by natefaubion** [comment]
I've verified that the package-set for core installs and the TryPureScript module compiles. Is there anything else for the main branch before venturing into gh-pages?

**Comment by natefaubion** [comment]
I've updated this to 0.12.1

**Comment by blinky3713** [comment]
What's the status with this and #127, are we able to get a working release with 0.12.1 sometime soon?

**Comment by hdgarrood** [comment]
I suspect the failure is due to there not being any output for too long leading to Travis terminating the build. I'd argue that the best thing to do for now is just to ignore the CI failure.

**Comment by natefaubion** [comment]
I've made updates for 0.12.3.

**Pull request merged**
